version: '3.8'
services:
  # app:
  #   build: .
  #   ports:
  #     - '3000:3000'
  #   environment:
  #     POSTGRES_HOST: db
  #     POSTGRES_PORT: ${POSTGRES_PORT}
  #     POSTGRES_USERNAME: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DB}
  #   depends_on:
  #     - db
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   command: npm run start:dev

  db:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: malimax
      POSTGRES_PASSWORD: Dinu9698@
      POSTGRES_DB: pss
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:  